/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_jesusr;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesus
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    ArrayList<Consola> console = new ArrayList();
 DefaultListModel<String> modelo=new DefaultListModel<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        POPM = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        Games = new javax.swing.JMenuItem();
        Modify = new javax.swing.JDialog();
        Consola1 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        IdPort1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        FabPort1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        AñosPort1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        PricePort1 = new javax.swing.JTextField();
        ModPort1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        PortBut1 = new javax.swing.JButton();
        Bateria1 = new javax.swing.JTextField();
        Estuche1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        TamPort1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        IdEsta1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        FabEsta1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        AñosEsta1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        PrecioEsta1 = new javax.swing.JTextField();
        ModeloEsta1 = new javax.swing.JTextField();
        ButonE1 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        Controles1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        Alma1 = new javax.swing.JTextField();
        Conexion1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        ListaGames = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GameList = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        GameName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        GameDes = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        DateGame = new com.toedter.calendar.JDateChooser();
        PriceGame = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        EstadoGame = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        RentGame = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        AddGame = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        CanGame = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        AgregarGame = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsolaTab = new javax.swing.JTable();
        Consola = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        IdPort = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FabPort = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AñosPort = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PricePort = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ModPort = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        PortBut = new javax.swing.JButton();
        Bateria = new javax.swing.JTextField();
        Estuche = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TamPort = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IdEsta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FabEsta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AñosEsta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PrecioEsta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ModeloEsta = new javax.swing.JTextField();
        ButonE = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Controles = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Alma = new javax.swing.JTextField();
        Conexion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        POPM.add(Modificar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        POPM.add(Eliminar);

        Games.setText("GAMES");
        Games.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GamesActionPerformed(evt);
            }
        });
        POPM.add(Games);

        jLabel21.setText("Identificacion");

        jLabel22.setText("Fabricante");

        jLabel23.setText("Años de Uso");

        jLabel24.setText("Precio");

        jLabel26.setText("Modelo");

        PortBut1.setText("Portatil");
        PortBut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PortBut1MouseClicked(evt);
            }
        });
        PortBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortBut1ActionPerformed(evt);
            }
        });

        jLabel27.setText("Estuche");

        jLabel28.setText("Tamaño");

        jLabel29.setText("Bateria");

        jLabel30.setText("P/M/G");

        jLabel31.setText("Y/N");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FabPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addComponent(IdPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AñosPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PricePort1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TamPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estuche1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(PortBut1)
                        .addGap(9, 9, 9)))
                .addGap(18, 18, 18))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(IdPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(FabPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(AñosPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(PricePort1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(TamPort1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(Bateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Estuche1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addGap(5, 5, 5)
                        .addComponent(PortBut1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Crear Portatil", jPanel10);

        jLabel32.setText("Identificacion");

        jLabel33.setText("Fabricante");

        jLabel34.setText("Años de Uso");

        jLabel35.setText("Precio");

        ButonE1.setText("Estacionaria");
        ButonE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonE1MouseClicked(evt);
            }
        });
        ButonE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonE1ActionPerformed(evt);
            }
        });

        jLabel37.setText("Modelo");

        jLabel38.setText("Almacenamiento");

        jLabel39.setText("Conexion");

        jLabel40.setText("Controles");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FabEsta1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addGap(18, 18, 18)
                            .addComponent(IdEsta1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AñosEsta1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ModeloEsta1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PrecioEsta1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButonE1)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Controles1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Conexion1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Alma1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(IdEsta1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(FabEsta1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(AñosEsta1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(Controles1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(Alma1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Conexion1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(PrecioEsta1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModeloEsta1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addContainerGap(92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(ButonE1)
                        .addContainerGap(101, Short.MAX_VALUE))))
        );

        jTabbedPane5.addTab("Crear Estacionaria", jPanel11);

        javax.swing.GroupLayout Consola1Layout = new javax.swing.GroupLayout(Consola1);
        Consola1.setLayout(Consola1Layout);
        Consola1Layout.setHorizontalGroup(
            Consola1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Consola1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );
        Consola1Layout.setVerticalGroup(
            Consola1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Consola1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ModifyLayout = new javax.swing.GroupLayout(Modify.getContentPane());
        Modify.getContentPane().setLayout(ModifyLayout);
        ModifyLayout.setHorizontalGroup(
            ModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(ModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModifyLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Consola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ModifyLayout.setVerticalGroup(
            ModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(ModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModifyLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Consola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GameList.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(GameList);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 450));

        jLabel25.setText("Lanzamiento");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 80, 40));

        GameName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameNameActionPerformed(evt);
            }
        });
        jPanel3.add(GameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 100, -1));

        GameDes.setColumns(20);
        GameDes.setRows(5);
        jScrollPane3.setViewportView(GameDes);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 240, 90));

        jLabel36.setText("Nombre");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 80, 40));

        jLabel41.setText("Descripcion");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 80, 40));

        DateGame.setDateFormatString("dd/ MM /YYYY");
        jPanel3.add(DateGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 310, -1));

        PriceGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceGameActionPerformed(evt);
            }
        });
        jPanel3.add(PriceGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 120, -1));

        jLabel42.setText("Precio");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 80, 40));

        EstadoGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoGameActionPerformed(evt);
            }
        });
        jPanel3.add(EstadoGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 120, -1));

        jLabel43.setText("Estado  N/U");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 80, 40));

        RentGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentGameActionPerformed(evt);
            }
        });
        jPanel3.add(RentGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 120, -1));

        jLabel44.setText("Rentable S/N");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 80, 40));

        AddGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGameActionPerformed(evt);
            }
        });
        jPanel3.add(AddGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 120, -1));

        jLabel45.setText("Agregado S/N");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 80, 40));

        CanGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanGameActionPerformed(evt);
            }
        });
        jPanel3.add(CanGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 120, -1));

        jLabel46.setText("Cantidad");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 80, 40));

        AgregarGame.setText("Agregar");
        AgregarGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarGameMouseClicked(evt);
            }
        });
        jPanel3.add(AgregarGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        javax.swing.GroupLayout ListaGamesLayout = new javax.swing.GroupLayout(ListaGames.getContentPane());
        ListaGames.getContentPane().setLayout(ListaGamesLayout);
        ListaGamesLayout.setHorizontalGroup(
            ListaGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        ListaGamesLayout.setVerticalGroup(
            ListaGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(51, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConsolaTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Modelo", "Años", "Precio", "Consola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ConsolaTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsolaTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ConsolaTab);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Listar todo", jPanel2);

        jLabel7.setText("Identificacion");

        jLabel8.setText("Fabricante");

        jLabel9.setText("Años de Uso");

        jLabel10.setText("Precio");

        jLabel11.setText("Modelo");

        jLabel12.setText("Modelo");

        PortBut.setText("Portatil");
        PortBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PortButMouseClicked(evt);
            }
        });
        PortBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortButActionPerformed(evt);
            }
        });

        jLabel13.setText("Estuche");

        jLabel14.setText("Tamaño");

        jLabel15.setText("Bateria");

        jLabel19.setText("P/M/G");

        jLabel20.setText("Y/N");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FabPort, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(IdPort, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AñosPort, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModPort, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PricePort, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TamPort, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estuche, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(PortBut)
                        .addGap(9, 9, 9)))
                .addGap(18, 18, 18))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(IdPort, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(FabPort, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(AñosPort, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(PricePort, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModPort, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(64, 64, 64)
                        .addComponent(jLabel11))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TamPort, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Estuche, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(5, 5, 5)
                        .addComponent(PortBut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Crear Portatil", jPanel9);

        jLabel1.setText("Identificacion");

        jLabel2.setText("Fabricante");

        jLabel3.setText("Años de Uso");

        jLabel4.setText("Precio");

        jLabel5.setText("Modelo");

        ButonE.setText("Estacionaria");
        ButonE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonEMouseClicked(evt);
            }
        });
        ButonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonEActionPerformed(evt);
            }
        });

        jLabel6.setText("Modelo");

        jLabel16.setText("Almacenamiento");

        jLabel17.setText("Conexion");

        jLabel18.setText("Controles");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FabEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(IdEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AñosEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ModeloEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PrecioEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButonE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Controles, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Conexion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Alma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IdEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(FabEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(AñosEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Controles, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Alma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Conexion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PrecioEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModeloEsta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(ButonE)
                        .addGap(8, 8, 8)))
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Crear Estacionaria", jPanel8);

        javax.swing.GroupLayout ConsolaLayout = new javax.swing.GroupLayout(Consola);
        Consola.setLayout(ConsolaLayout);
        ConsolaLayout.setHorizontalGroup(
            ConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        ConsolaLayout.setVerticalGroup(
            ConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Consola", Consola);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 470, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButonEActionPerformed

    private void PortButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortButActionPerformed

    private void ButonEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonEMouseClicked
       String tipo="Estacionaria";
        String id = IdEsta.getText();
        boolean Valid = false;
        String fab = FabEsta.getText();
        String mod = ModeloEsta.getText();
        double price = Double.parseDouble(PrecioEsta.getText());
        int years = Integer.parseInt(AñosEsta.getText());
        int cont = Integer.parseInt(Controles.getText());
        int manag = Integer.parseInt(Alma.getText());
        String Conex = Conexion.getText();
        if (id.length()== 8&& id.substring(0, 4).matches("\\d+") && (id.substring(4).matches("[A-Z]+"))) {
            JOptionPane.showMessageDialog(null, "OK");
            Valid = true;
            console.add(new Estacionaria(cont, manag, Conex,id , fab, mod, years, price,tipo));

            IdEsta.setText("");
            FabEsta.setText("");
            ModeloEsta.setText("");
            PrecioEsta.setText("");
            AñosEsta.setText("");
            Controles.setText("");
            Alma.setText("");
            Conexion.setText("");
            
            
             try {
                ConsolaTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Modelo", "Años", "Precio", "Consola"
            }
        ));
            DefaultTableModel Mike= (DefaultTableModel)ConsolaTab.getModel();
          
            ConsolaTab.setModel(Mike);

            
            for (Consola t : console) {
                Object[] row = {t.getIdentificación(), t.getFabricante(), t.getModelo(),t.getAñouso(),t.getPrecio(),t.getType()};
                DefaultTableModel modelo = (DefaultTableModel) ConsolaTab.getModel();
                modelo.addRow(row);
                ConsolaTab.setModel(modelo);            
            }
            

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        } else {
            JOptionPane.showMessageDialog(null, "Incorrecto");
            Valid = false;
        }


    }//GEN-LAST:event_ButonEMouseClicked

    private void PortButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PortButMouseClicked
         String tipo="Portatil";
        String idp = IdPort.getText();
        boolean Valid = false;
        String fabp = FabPort.getText();
        String Mod = ModPort.getText();
        double pricep = Double.parseDouble(PricePort.getText());
        String tam = TamPort.getText().toLowerCase();
        int bat = Integer.parseInt(Bateria.getText());
        String es = Estuche.getText().toLowerCase();
        int years = Integer.parseInt(AñosPort.getText());
        boolean mike = false;
        switch (es) {
            case "y": {
                mike = true;

            }
            break;
            case "n": {
                mike = false;
            }
            break;
            default: {
                JOptionPane.showMessageDialog(null, "No valido");

            }
            break;
        }
        if (idp.length() == 8&& idp.substring(0, 4).matches("\\d+") && (idp.substring(4).matches("[A-Z]+"))) {
            JOptionPane.showMessageDialog(null, "OK");
            Valid = true;

            console.add(new Portatil(tam, bat, mike, idp, fabp, Mod, years, pricep,tipo));
            IdPort.setText("");
            FabPort.setText("");
            PricePort.setText("");
            TamPort.setText("");
            Bateria.setText("");
            Estuche.setText("");
            AñosPort.setText("");
            ModPort.setText("");
            
            
            try {
                ConsolaTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Modelo", "Años", "Precio", "Consola"
            }
        ));
            DefaultTableModel Mike= (DefaultTableModel)ConsolaTab.getModel();
          
            ConsolaTab.setModel(Mike);

            
            for (Consola t : console) {
                Object[] row = {t.getIdentificación(), t.getFabricante(), t.getModelo(),t.getAñouso(),t.getPrecio(),t.getType()};
                DefaultTableModel modelo = (DefaultTableModel) ConsolaTab.getModel();
                modelo.addRow(row);
                ConsolaTab.setModel(modelo);            
            }
            

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        } else {
            JOptionPane.showMessageDialog(null, "Incorrecto");
            Valid = false;
        }


    }//GEN-LAST:event_PortButMouseClicked

    private void ConsolaTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsolaTabMouseClicked
        if (evt.isMetaDown()) {
            if (ConsolaTab.getSelectedRow()>=0) {
                POPM.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_ConsolaTabMouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        Modify.setModal(true);
        Modify.pack();
        Modify.setLocationRelativeTo(this);
        Modify.setVisible(true);
    }//GEN-LAST:event_ModificarActionPerformed

    private void PortBut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PortBut1MouseClicked
       
        String tipo="Portatil";
        String idp = IdPort1.getText();
        boolean Valid = false;
        String fabp = FabPort1.getText();
        String Mod = ModPort1.getText();
        double pricep = Double.parseDouble(PricePort1.getText());
        String tam = TamPort1.getText().toLowerCase();
        int bat = Integer.parseInt(Bateria1.getText());
        String es = Estuche1.getText().toLowerCase();
        int years = Integer.parseInt(AñosPort1.getText());
        boolean mike = false;
        switch (es) {
            case "y": {
                mike = true;

            }
            break;
            case "n": {
                mike = false;
            }
            break;
            default: {
                JOptionPane.showMessageDialog(null, "No valido");

            }
            break;
        }
        if (idp.length() == 8&& idp.substring(0, 4).matches("\\d+") && (idp.substring(4).matches("[A-Z]+"))) {
            JOptionPane.showMessageDialog(null, "OK");
            Valid = true;
            console.remove(ConsolaTab.getSelectedRow());

            console.add(ConsolaTab.getSelectedRow(),new Portatil(tam, bat, mike, idp, fabp, Mod, years, pricep,tipo));
            IdPort1.setText("");
            FabPort1.setText("");
            PricePort1.setText("");
            TamPort1.setText("");
            Bateria1.setText("");
            Estuche1.setText("");
            AñosPort1.setText("");
            ModPort1.setText("");
             Modify.dispose();
            
            
            try {
                ConsolaTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Modelo", "Años", "Precio", "Consola"
            }
        ));
            DefaultTableModel Mike= (DefaultTableModel)ConsolaTab.getModel();
          
            ConsolaTab.setModel(Mike);

            
            for (Consola t : console) {
                Object[] row = {t.getIdentificación(), t.getFabricante(), t.getModelo(),t.getAñouso(),t.getPrecio(),t.getType()};
                DefaultTableModel modelo = (DefaultTableModel) ConsolaTab.getModel();
                modelo.addRow(row);
                ConsolaTab.setModel(modelo);            
            }
            

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        } else {
            JOptionPane.showMessageDialog(null, "Incorrecto");
            Valid = false;
        }

        
        
        
    }//GEN-LAST:event_PortBut1MouseClicked

    private void PortBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortBut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortBut1ActionPerformed

    private void ButonE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonE1MouseClicked
       
        String tipo="Estacionaria";
        String id = IdEsta1.getText();
        boolean Valid = false;
        String fab = FabEsta1.getText();
        String mod = ModeloEsta1.getText();
        double price = Double.parseDouble(PrecioEsta1.getText());
        int years = Integer.parseInt(AñosEsta1.getText());
        int cont = Integer.parseInt(Controles1.getText());
        int manag = Integer.parseInt(Alma1.getText());
        String Conex = Conexion1.getText();
        if (id.length()== 8&& id.substring(0, 4).matches("\\d+") && (id.substring(4).matches("[A-Z]+"))) {
            JOptionPane.showMessageDialog(null, "OK");
            Valid = true;
            console.remove(ConsolaTab.getSelectedRow());
            console.add(ConsolaTab.getSelectedRow(),new Estacionaria(cont, manag, Conex,id , fab, mod, years, price,tipo));

            IdEsta1.setText("");
            FabEsta1.setText("");
            ModeloEsta1.setText("");
            PrecioEsta1.setText("");
            AñosEsta1.setText("");
            Controles1.setText("");
            Alma1.setText("");
            Conexion1.setText("");
            
            Modify.dispose();
             try {
                ConsolaTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Modelo", "Años", "Precio", "Consola"
            }
        ));
            DefaultTableModel Mike= (DefaultTableModel)ConsolaTab.getModel();
          
            ConsolaTab.setModel(Mike);

            
            for (Consola t : console) {
                Object[] row = {t.getIdentificación(), t.getFabricante(), t.getModelo(),t.getAñouso(),t.getPrecio(),t.getType()};
                DefaultTableModel modelo = (DefaultTableModel) ConsolaTab.getModel();
                modelo.addRow(row);
                ConsolaTab.setModel(modelo);            
            }
            

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        } else {
            JOptionPane.showMessageDialog(null, "Incorrecto");
            Valid = false;
        }
        
        
        
        
    }//GEN-LAST:event_ButonE1MouseClicked

    private void ButonE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButonE1ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
       int op=  JOptionPane.showConfirmDialog(this, "¿Seguro?","Eliminar",JOptionPane.YES_NO_OPTION);
        if (op==JOptionPane.YES_OPTION) {
            console.remove(ConsolaTab.getSelectedRow());
           
            
            try {
                ConsolaTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Modelo", "Años", "Precio", "Consola"
            }
        ));
            DefaultTableModel Mike= (DefaultTableModel)ConsolaTab.getModel();
          
            ConsolaTab.setModel(Mike);

            
            for (Consola t : console) {
                Object[] row = {t.getIdentificación(), t.getFabricante(), t.getModelo(),t.getAñouso(),t.getPrecio(),t.getType()};
                DefaultTableModel modelo = (DefaultTableModel) ConsolaTab.getModel();
                modelo.addRow(row);
                ConsolaTab.setModel(modelo);            
            }
            

        } catch (Exception ex) {
            ex.printStackTrace();
        }
            
        }else{
            JOptionPane.showMessageDialog(null, "Adios");
        }
         JOptionPane.showMessageDialog(null, "Logrado Exitosamente");
    }//GEN-LAST:event_EliminarActionPerformed

    private void GameNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GameNameActionPerformed

    private void PriceGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceGameActionPerformed

    private void EstadoGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoGameActionPerformed

    private void RentGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RentGameActionPerformed

    private void AddGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddGameActionPerformed

    private void CanGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CanGameActionPerformed

    private void AgregarGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarGameMouseClicked
        String Game= GameName.getText();
        String des=GameDes.getText();
        double price= Double.parseDouble(PriceGame.getText());
        String State= EstadoGame.getText().toLowerCase();
        boolean rent1=false;
        String rent= RentGame.getText().toLowerCase();
        switch (rent) {
            case "s":{
                rent1=true;
            }
                
                break;
            case "n":{
                rent1=false;
            }
            default:
                JOptionPane.showMessageDialog(null, "No valido");
                break;
        }
        boolean add1=false;
        String add= AddGame.getText().toLowerCase();
        switch (add) {
            case "s":{
                add1=true;
            }
                
                break;
            case "n":{
                add1=false;
            }
            default:
                JOptionPane.showMessageDialog(null, "No valido");
                break;
        }
        int Cant= Integer.parseInt(CanGame.getText());
        Date fecha= DateGame.getDate();
   
        console.get(ConsolaTab.getSelectedRow()).getGame().add(new Juego(Game, des, State, price, fecha, Cant, rent1, add1));
        try {
                ConsolaTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Modelo", "Años", "Precio", "Consola"
            }
        ));
            DefaultTableModel Mike= (DefaultTableModel)ConsolaTab.getModel();
          
            ConsolaTab.setModel(Mike);

            
            for (Consola t : console) {
                Object[] row = {t.getIdentificación(), t.getFabricante(), t.getModelo(),t.getAñouso(),t.getPrecio(),t.getType()};
                DefaultTableModel modelo = (DefaultTableModel) ConsolaTab.getModel();
                modelo.addRow(row);
                ConsolaTab.setModel(modelo);            
            }
            
            
             GameList.setModel(modelo);
        modelo.addElement(GameName.getText().trim());        
                
            
            
            
            
            
            
            
            
            

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        GameName.setText("");
        GameDes.setText("");
        PriceGame.setText("");
        DateGame.setDate(new Date());
        RentGame.setText("");
        EstadoGame.setText("");
        CanGame.setText("");
        AddGame.setText("");
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_AgregarGameMouseClicked

    private void GamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamesActionPerformed
         ListaGames.setModal(true);
        ListaGames.pack();
        ListaGames.setLocationRelativeTo(this);
        ListaGames.setVisible(true);
    }//GEN-LAST:event_GamesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddGame;
    private javax.swing.JButton AgregarGame;
    private javax.swing.JTextField Alma;
    private javax.swing.JTextField Alma1;
    private javax.swing.JTextField AñosEsta;
    private javax.swing.JTextField AñosEsta1;
    private javax.swing.JTextField AñosPort;
    private javax.swing.JTextField AñosPort1;
    private javax.swing.JTextField Bateria;
    private javax.swing.JTextField Bateria1;
    private javax.swing.JButton ButonE;
    private javax.swing.JButton ButonE1;
    private javax.swing.JTextField CanGame;
    private javax.swing.JTextField Conexion;
    private javax.swing.JTextField Conexion1;
    private javax.swing.JPanel Consola;
    private javax.swing.JPanel Consola1;
    private javax.swing.JTable ConsolaTab;
    private javax.swing.JTextField Controles;
    private javax.swing.JTextField Controles1;
    private com.toedter.calendar.JDateChooser DateGame;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JTextField EstadoGame;
    private javax.swing.JTextField Estuche;
    private javax.swing.JTextField Estuche1;
    private javax.swing.JTextField FabEsta;
    private javax.swing.JTextField FabEsta1;
    private javax.swing.JTextField FabPort;
    private javax.swing.JTextField FabPort1;
    private javax.swing.JTextArea GameDes;
    private javax.swing.JList<String> GameList;
    private javax.swing.JTextField GameName;
    private javax.swing.JMenuItem Games;
    private javax.swing.JTextField IdEsta;
    private javax.swing.JTextField IdEsta1;
    private javax.swing.JTextField IdPort;
    private javax.swing.JTextField IdPort1;
    private javax.swing.JDialog ListaGames;
    private javax.swing.JTextField ModPort;
    private javax.swing.JTextField ModPort1;
    private javax.swing.JTextField ModeloEsta;
    private javax.swing.JTextField ModeloEsta1;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JDialog Modify;
    private javax.swing.JPopupMenu POPM;
    private javax.swing.JButton PortBut;
    private javax.swing.JButton PortBut1;
    private javax.swing.JTextField PrecioEsta;
    private javax.swing.JTextField PrecioEsta1;
    private javax.swing.JTextField PriceGame;
    private javax.swing.JTextField PricePort;
    private javax.swing.JTextField PricePort1;
    private javax.swing.JTextField RentGame;
    private javax.swing.JTextField TamPort;
    private javax.swing.JTextField TamPort1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    // End of variables declaration//GEN-END:variables
}
